#!/bin/bash

set -ueo pipefail

# setup a user with the same userid as /myapp/config.xml


# fix'em all up
mkuser() {
if [ -d "/myapp" ]; then
	uid=$(stat -c %u /myapp)
	gid=$(stat -c %g /myapp)
	groupadd -g "$gid" ionic
	useradd -M -u "$uid" -g "$gid" -d /myapp ionic
else
	cat <<dog
Usage:
\$ eval "\$(docker run --rm brimstone/ionic bash")"

Then use \`ionic\` as normal.
dog
	exit 1
fi
}

VERB="${1:-}"

case "$VERB" in
	bash)
	cat <<dog
ionic(){
	docker run --rm -t -i \
	-e "DISPLAY=unix\$DISPLAY" \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v "\$PWD:/myapp" \
	\$([ "\$1" = "serve" ] && echo "-p 8100:8100 -p 35729:35729") \
	brimstone/ionic "\$@"
}
dog
exit
	;;
	root)
	exec /bin/bash
	;;
	"")
	mkuser
	exec su ionic -c /bin/bash
	;;
	*)
	mkuser
	cd /myapp
	su ionic -c "ionic $*"
	rm .ionic/ionic.config
	rmdir .ionic
	;;
esac
