#!/bin/bash

set -ueo pipefail

# setup a user with the same userid as /myapp/config.xml


VERB="${1:-}"

case "$VERB" in
	bash)
	cat <<dog
ionic(){
	docker run --rm -t -i \
	-e "DISPLAY=unix\$DISPLAY" \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v "\$PWD:/myapp" \
	-u "\$UID:\$GID" \
	\$([ "\$1" = "serve" ] && echo "-p 8100:8100 -p 35729:35729") \
	brimstone/ionic "\$@"
}
dog
exit
	;;
	"")
	exec /bin/bash
	;;
	*)
	if [ ! -d "/myapp" ]; then
		cat <<dog
Usage:
\$ eval "\$(docker run --rm brimstone/ionic bash)"

Then use \`ionic\` as normal.
dog
		exit 1
	fi
	cd /myapp
	ionic "$@"
	;;
esac
